### ISSUE TITLE
HUnit-Plus-1.0.1 fails to compile with base 4.8

### ISSUE THREAD

**Issue by peti** [emc2/HUnit-Plus#21]
Citing from http://hydra.cryp.to/build/912674/nixlog/1/raw:

~~~~~~
Building HUnit-Plus-1.0.1...
Preprocessing library HUnit-Plus-1.0.1...
[ 1 of 10] Compiling Test.HUnitPlus.Terminal ( src/Test/HUnitPlus/Terminal.hs, dist/build/Test/HUnitPlus/Terminal.o )
[ 2 of 10] Compiling Test.HUnitPlus.Filter ( src/Test/HUnitPlus/Filter.hs, dist/build/Test/HUnitPlus/Filter.o )
[ 3 of 10] Compiling Test.HUnitPlus.Reporting ( src/Test/HUnitPlus/Reporting.hs, dist/build/Test/HUnitPlus/Reporting.o )

src/Test/HUnitPlus/Reporting.hs:27:1: Warning:
    The import of ‘Data.Word’ is redundant
      except perhaps to import instances from ‘Data.Word’
    To import instances alone, use: import Data.Word()

<no location info>: 
Failing due to -Werror.
~~~~~~~

**Comment by emc2** [comment]
Apparently base 4.8 includes Word in the Prelude, which breaks the build due to the use of -Werror.

What version of base are you using?

**Comment by peti** [comment]
You'll find all the version information in the build log I linked to.

**Comment by emc2** [comment]
As suspected, base-4.8 is to blame.

**Comment by emc2** [comment]
Updated base version to < 4.8.  This will have to do for now; actively changing base compatibility shouldn't be done as a bug-fix.

**Comment by peti** [comment]
Well, this change certainly doesn't help us in NixOS. Since it's broken, I'll remove your package from the distribution.

**Comment by emc2** [comment]
I'll consider removing the -Werror flag for the next minor version, since there seems to be no way to avoid warnings across all 4.* versions of base :(

**Comment by emc2** [comment]
1.1-RELEASE builds with base-4.8

**Comment by emc2** [comment]
Closing for good.
