### ISSUE TITLE
testinfo initialized to undefined

### ISSUE THREAD

**Issue by Lysxia** [emc2/HUnit-Plus#23]
I am using HUnit-Plus to write tests to be run with `stack test`, with `type: detailed-0.9`, and ran into `undefined`, even on a test as simple as:

    tests :: IO [Test]
    tests = return ["testName" ~: True ~?= True]

And I traced it to [L133 of Test.HUnitPlus.Base](https://github.com/emc2/HUnit-Plus/blob/master/src/Test/HUnitPlus/Base.hs#L133):

    testinfo = unsafePerformIO $! newIORef undefined

Indeed, `testinfo` is used by the `~?=` operator, but is reset only by `executeTest`, which I don't call since `cabal` or  `stack` should take care of running the tests.

Initializing it to a defined value seems to fix it.

**Comment by emc2** [comment]
Applied suggested fix, please confirm that it works

**Comment by Lysxia** [comment]
Excellent! Cheers!

**Comment by emc2** [comment]
I will put out a new release to Hackage then.
